### ISSUE TITLE
methods "calcincmatrix_o" and "Export IncMatrix" 

### ISSUE THREAD

**Issue by Zecao** [PMeira/dss_sharp#8]
Hello, Paulo,
There are 2 methods I frequently use in DSSText.Command interface that arent implemented yet in the dss_sharp:  "calcincmatrix_o" and "Export IncMatrix" 
If you can provide these on a future version it will be great. 
Thanks 
Ezequiel

**Comment by PMeira** [comment]
Hi, Ezequiel,
I had already ported the main code for those before (back in October), so just needed to expose the DSS commands from V8 to V7: `CalcIncMatrix`, `CalcIncMatrix_O`, `Refine_BusLevels`, `CalcLaplacian` -- https://github.com/dss-extensions/dss_capi/commit/d67f9dc5dfae166d1d53f7c85b95eb54796907c6

The `Export` commands were already ported correctly. I ran a basic test now and got the same results as COM Version 8, so it should be fine -- be sure to check though.

You're using v0.10.1a1, right? Since this doesn't change the API, you should be able to grab the fresh `dss_capi_v7.dll` from [AppVeyor](https://ci.appveyor.com/api/buildjobs/f0sd3hrh6tinf89p/artifacts/dss_capi__win_x64.zip) and replace your local `dss_capi.dll`. For this version also copy `libwinpthread-1.dll` and `libklusolve.dll` since they contain a new function --  this function made DSS C-API 7-20% faster.

There is also a family of methods like `Solution_Get_IncMatrix` that isn't properly replicated in C#:

https://github.com/dss-extensions/dss_capi/blob/db2936c200a42564be387a1c923ebd69d465eabc/include/v7/dss_capi.h#L4647

Let me know if you have any use for those and I'll expose them sooner. And thanks for reporting these issues.

**Comment by Zecao** [comment]
Hi, Paulo, 
I followed your instructions carefully, but I'm getting a exception in both methods from the  <code>dss_sharp.dll</code>. Yes, Im using the v0.10.1a1.

**Comment by PMeira** [comment]
@Zecao Maybe I forgot something, try `bin\Debug\simple_test.exe` from this very crude test:
[simple_test.zip](https://github.com/dss-extensions/dss_sharp/files/2948890/simple_test.zip)

The `DSS.Version` should be this:
```DSS C-API Library version 0.10.3 revision d67f9dc5dfae166d1d53f7c85b95eb54796907c6 based on OpenDSS SVN 2504 (v7/classic variation) MVMULT (64-bit build); License Status: Open ```

**Comment by Zecao** [comment]
It´s working, man! :)
I didn't understand why it doesn't work before (but, as I'm working in a different computer right now, it could be something related to that). Also, I did 2 modifications to run the test:  
1. I added a line with the data path, because of Redirect to IEEELineCodes.dss inside the IEEE13Nodeckt file. 
2. I had to comment the lines beginning with "*/" in the IEEE13Nodeckt file, because they were generating exceptions (it gave me the error number 302).
Thank you!

**Comment by PMeira** [comment]
Nice! You probably had multiple copies of the DLL and it was picking the wrong one.

> I had to comment the lines beginning with "*/" in the IEEE13Nodeckt file, because they were generating exceptions (it gave me the error number 302).

The redirect shouldn't be an issue either, but this issue with block comments is especially strange. I'll try to look into it this week.

**Comment by PMeira** [comment]
I forgot to close this issue before. I'll mention that the reworked version (with includes mapping DSS.Error to .NET exceptions) should land soon and should make debugging errors in DSS scripts much easier: https://github.com/dss-extensions/dss_sharp/pull/11
